import { jsPDF } from 'jspdf';

const COLORS = {
  bg: [5, 5, 16],
  headerBar: [0, 212, 255],
  neonBlue: [0, 212, 255],
  neonPurple: [168, 85, 247],
  white: [255, 255, 255],
  dimWhite: [180, 180, 200],
  gray: [120, 120, 140],
};

const sections = [
  { key: 'summary', title: 'SUMMARY' },
  { key: 'marketDemand', title: 'MARKET DEMAND' },
  { key: 'targetCustomers', title: 'TARGET CUSTOMERS' },
  { key: 'competitorAnalysis', title: 'COMPETITOR ANALYSIS' },
  { key: 'uniqueValueProposition', title: 'UNIQUE VALUE PROPOSITION' },
  { key: 'monetizationStrategy', title: 'MONETIZATION STRATEGY' },
  { key: 'risksAndChallenges', title: 'RISKS & CHALLENGES' },
  { key: 'mvpRoadmap', title: 'MVP ROADMAP' },
  { key: 'suggestedTechStack', title: 'SUGGESTED TECH STACK' },
  { key: 'successScore', title: 'SUCCESS SCORE' },
];

export function generatePDF(idea, country, analysis, date) {
  const doc = new jsPDF('p', 'mm', 'a4');
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let y = 0;
  let pageNum = 1;

  function drawBackground() {
    doc.setFillColor(...COLORS.bg);
    doc.rect(0, 0, pageWidth, pageHeight, 'F');
  }

  function drawFooter() {
    doc.setFontSize(8);
    doc.setTextColor(...COLORS.gray);
    doc.text('Generated by Startup.AI', margin, pageHeight - 10);
    doc.text(`Page ${pageNum}`, pageWidth - margin, pageHeight - 10, { align: 'right' });
  }

  function addNewPage() {
    drawFooter();
    doc.addPage();
    pageNum++;
    drawBackground();
    y = margin;
  }

  function checkPageBreak(requiredSpace = 30) {
    if (y + requiredSpace > pageHeight - 20) {
      addNewPage();
    }
  }

  // ===== Page 1 =====
  drawBackground();

  // Header bar
  doc.setFillColor(...COLORS.headerBar);
  doc.rect(0, 0, pageWidth, 4, 'F');

  // Title
  y = 30;
  doc.setFontSize(22);
  doc.setTextColor(...COLORS.white);
  doc.setFont('helvetica', 'bold');
  doc.text('AI STARTUP ANALYSIS REPORT', margin, y);

  // Subtitle
  y += 12;
  doc.setFontSize(11);
  doc.setTextColor(...COLORS.dimWhite);
  doc.setFont('helvetica', 'normal');

  const ideaText = idea.length > 80 ? idea.substring(0, 80) + '...' : idea;
  doc.text(ideaText, margin, y);

  y += 7;
  doc.setFontSize(9);
  doc.setTextColor(...COLORS.gray);
  const formattedDate = date ? new Date(date).toLocaleDateString('en-US', {
    year: 'numeric', month: 'long', day: 'numeric'
  }) : new Date().toLocaleDateString();
  doc.text(`Country: ${country}  •  Generated: ${formattedDate}`, margin, y);

  // Divider
  y += 8;
  doc.setDrawColor(...COLORS.neonBlue);
  doc.setLineWidth(0.5);
  doc.line(margin, y, pageWidth - margin, y);
  y += 12;

  // ===== Sections =====
  sections.forEach((section, index) => {
    checkPageBreak(40);

    // Section heading
    const headingColor = index % 2 === 0 ? COLORS.neonBlue : COLORS.neonPurple;
    doc.setFontSize(11);
    doc.setTextColor(...headingColor);
    doc.setFont('helvetica', 'bold');
    doc.text(section.title, margin, y);
    y += 7;

    // Section body
    let bodyText = '';
    if (section.key === 'successScore') {
      bodyText = `Score: ${analysis[section.key]} / 100`;
    } else {
      bodyText = analysis[section.key] || 'N/A';
    }

    doc.setFontSize(9.5);
    doc.setTextColor(...COLORS.dimWhite);
    doc.setFont('helvetica', 'normal');

    const lines = doc.splitTextToSize(bodyText, contentWidth);
    for (const line of lines) {
      checkPageBreak(7);
      doc.text(line, margin, y);
      y += 5;
    }

    y += 8;
  });

  // Final footer
  drawFooter();

  // Save
  const timestamp = Date.now();
  doc.save(`startup-analysis-${timestamp}.pdf`);
}
